#!/bin/sh
#$cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions


#runApplication reconstructPar -newTimes

while true; do
    runApplication reconstructPar -newTimes
    rm log.reconstructPar
    sleep 300
done

# ----------------------------------------------------------------- end-of-file
