#!/bin/bash

sudo mkdir -p /media/joseph/brahms 
sudo mkdir -p /media/joseph/bach
sudo mkdir -p /media/joseph/backup
sudo mkdir -p /media/joseph/mozart
sudo mkdir -p /media/joseph/work
sudo mkdir -p /media/joseph/haydn
sudo mkdir -p /media/joseph/home
sudo mkdir -p /mnt/nfs/palladiumHome
echo "mkdir media/nfs directories"
