#!/bin/bash

cp startScriptClient ../startScriptClient
echo "copy startScriptClient"
cp lubuntu-rc.xml ../.config/openbox/lubuntu-rc.xml
echo "copy lubuntu shortcuts"
cp vimrc ../.vimrc
echo "copy vimrc"
