#!/bin/bash

sudo mount 172.17.1.168:/media/joseph/mozart /mnt/nfs/mozart
sudo mount 172.17.1.168:/media/joseph/bach /mnt/nfs/bach
sudo mount 172.17.1.168:/home /mnt/nfs/home
sudo mount 172.17.1.168:/media/joseph/backup /mnt/nfs/backup
sudo mount 172.17.1.168:/media/joseph/work /mnt/nfs/work
sudo mount 172.17.1.168:/media/joseph/sky /mnt/nfs/sky
sudo mount 172.17.1.168:/media/joseph/sea /mnt/nfs/sea
sudo mount 172.17.1.168:/media/joseph/land /mnt/nfs/land

cd /media/
mount -t vboxsf Dropbox /media/windows-share/
cd ~
