#!/bin/bash
echo "
      J. Prince 11/14/2013
     "

USAGE="
      USAGE: $0 -m <name> 
"


#Use getopts to pass the flags to variables
while getopts "m:" opt; do
  case $opt in
    m) if [ -n $OPTARG ]; then
	MACHINE=$OPTARG
	fi
      ;;
    \?)
      echo "$USAGE" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

if [ $MACHINE == "aluminum" ]
    then
    echo "start aluminum"
    sudo mount /dev/sdc1 /media/joseph/mozart
    sudo mount /dev/sdg1 /media/joseph/sea
    sudo mount /dev/sdh1 /media/joseph/land
    sudo mount /dev/sdd1 /media/joseph/sky
    sudo mount /dev/sdf /media/joseph/work
    sudo mount /dev/sde1 /media/joseph/backup
    sudo mount /dev/sdb1 /media/joseph/bach

    sudo exportfs -a
    sudo service nfs-kernel-server start
    sudo /etc/init.d/opensmd start

fi

if [ $MACHINE == "gold" ]
    then
    echo "start cluster client caldera "
    sudo mount 172.17.1.168:/media/joseph/mozart /mnt/nfs/mozart
    sudo mount 172.17.1.168:/media/joseph/bach /mnt/nfs/bach
    sudo mount 172.17.1.168:/home /mnt/nfs/home
    sudo mount 172.17.1.168:/media/joseph/backup /mnt/nfs/backup
    sudo mount 172.17.1.168:/media/joseph/work /mnt/nfs/work
    sudo mount 172.17.1.168:/media/joseph/sky /mnt/nfs/sky
    sudo mount 172.17.1.168:/media/joseph/sea /mnt/nfs/sea
    sudo mount 172.17.1.168:/media/joseph/land /mnt/nfs/land

    sudo /etc/init.d/opensmd start
fi

if [ $MACHINE == "dell" ]
    then
    echo "start dell"
    sudo mount 172.17.1.168:/media/joseph/mozart /mnt/nfs/mozart
    sudo mount 172.17.1.168:/media/joseph/bach /mnt/nfs/bach
    cd /media/
    mount -t vboxsf Dropbox /media/windows-share/
    cd ~
fi

if [ $MACHINE == "precision" ]
    then
    echo "start precision"
    sudo mount 172.17.1.168:/media/joseph/mozart /mnt/nfs/mozart
    sudo mount 172.17.1.168:/media/joseph/bach /mnt/nfs/bach
    sudo mount 172.17.1.168:/home /mnt/nfs/home
    sudo mount 172.17.1.168:/media/joseph/backup /mnt/nfs/backup
    sudo mount 172.17.1.168:/media/joseph/work /mnt/nfs/work
    sudo mount 172.17.1.168:/media/joseph/sky /mnt/nfs/sky
    sudo mount 172.17.1.168:/media/joseph/sea /mnt/nfs/sea
    sudo mount 172.17.1.168:/media/joseph/land /mnt/nfs/land
    sudo ./.screenlayout/screen.sh
    sudo mount -t vboxsf K_DRIVE /media/joseph/arc
    sudo mount -t vboxsf J_DRIVE /media/joseph/joan
fi 

if [ $MACHINE == "envy" ]
    then
    echo "start envy"
    sudo exportfs -a
    sudo service nfs-kernel-server start
fi

if [ $MACHINE == "alpha" ]
    then
    echo "start alpha"
    sudo exportfs -a
    sudo service nfs-kernel-server start
fi
if [ $MACHINE == "bravo" ]
    then
    echo "start bravo"
    sudo mount alpha:/home /mnt/nfs/alphaHome
fi




