#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cat 0.org/U
cat 0.org/alpha.water
cat constant/transportProperties
cat constant/setFields


