#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

rm log.*
cp 0/alpha.water.orig 0/alpha.water

runApplication setFields

runApplication decomposePar -force


# ----------------------------------------------------------------- end-of-file
