#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

. $WM_PROJECT_DIR/bin/tools/RunFunctions

echo "started..."
./Allclean
echo "cleaned"
./Allmesh
echo "meshed"
./Allrun
echo "ready to run"
echo "running..."
foamJob -p -wait interFoam
echo "reconstructing..."
runApplication reconstructPar
echo "done"

